# Generated by Django 5.0.4 on 2024-04-24 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ayat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surah", models.IntegerField()),
                ("number", models.IntegerField()),
                ("ayat_in_surah", models.IntegerField()),
            ],
            options={
                "verbose_name": "Ayat",
                "verbose_name_plural": "Ayat",
            },
        ),
        migrations.CreateModel(
            name="UserHizbState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "Hizb User State",
                "verbose_name_plural": "Hizb User States",
            },
        ),
        migrations.CreateModel(
            name="UserJuzState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "Juz User State",
                "verbose_name_plural": "Juz User States",
            },
        ),
        migrations.CreateModel(
            name="HizbQuarter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("juz", models.IntegerField()),
                ("number", models.IntegerField()),
                ("ayat", models.ManyToManyField(to="ayats.ayat")),
            ],
            options={
                "verbose_name": "Hizb Quarter",
                "verbose_name_plural": "Hizb Quarters",
            },
        ),
        migrations.CreateModel(
            name="Juz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("ayat", models.ManyToManyField(to="ayats.ayat")),
            ],
            options={
                "verbose_name": "Juz",
                "verbose_name_plural": "Juz",
            },
        ),
        migrations.CreateModel(
            name="Ruku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("ayat", models.ManyToManyField(to="ayats.ayat")),
            ],
            options={
                "verbose_name": "Ruku",
                "verbose_name_plural": "Ruku",
            },
        ),
        migrations.CreateModel(
            name="UserAyatState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewed_date", models.DateTimeField(default=datetime.datetime.now)),
                ("expiration_date", models.DateTimeField()),
                ("weight", models.FloatField(default=1)),
                ("ayat", models.ManyToManyField(to="ayats.ayat")),
            ],
            options={
                "verbose_name": "User Ayat State",
                "verbose_name_plural": "User Ayat States",
            },
        ),
    ]
