# Generated by Django 5.0.4 on 2024-04-24 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ayats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userayatstate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userhizbstate",
            name="hizb",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ayats.hizbquarter"
            ),
        ),
        migrations.AddField(
            model_name="userhizbstate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userjuzstate",
            name="juz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ayats.juz"
            ),
        ),
        migrations.AddField(
            model_name="userjuzstate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="userhizbstate",
            index=models.Index(
                fields=["user", "hizb"], name="ayats_userh_user_id_fc7808_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userjuzstate",
            index=models.Index(
                fields=["user", "juz"], name="ayats_userj_user_id_53906a_idx"
            ),
        ),
    ]
